include:
  - project: viz/ci/gitlabpipelines
    file: index.yml


stages:
  - precheck
  - test-and-build
  - publish


.publish-braynscircuitstudio:
  extends: .publish-image-using-kaniko
  tags:
    - kubernetes
  variables:
    KUBERNETES_MEMORY_LIMIT: 2Gi
    KUBERNETES_MEMORY_REQUEST: 2Gi
    CI_REGISTRY_IMAGE: bbpgitlab.epfl.ch:5050/viz/brayns/braynscircuitstudio


check-branch-names:
  stage: precheck
  image:
    name: bash:latest
  script:
    - |-
      #!/bin/bash
      echo $SHELL
      echo "Package version: $NPM_PACKAGE_VERSION"
      echo "Source branch: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"
      echo "Target branch: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
      if [[ $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ ^(feature|bugfix) ]] && [[ $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master" ]]
      then
        echo "Branch name check failed. You can't merge branches into master that start with 'feature' or 'bugfix'"
        exit 1
      else
        echo "Branch name check - OK"
      fi
  rules:
    - if: $CI_MERGE_REQUEST_IID


build-docker-image:
  stage: test-and-build
  extends:
    - .build-image-using-kaniko
  tags:
    - kubernetes
  variables:
    KUBERNETES_MEMORY_LIMIT: 2Gi
    KUBERNETES_MEMORY_REQUEST: 2Gi
    CI_REGISTRY_IMAGE: bbpgitlab.epfl.ch:5050/viz/brayns/braynscircuitstudio


# Pushing a new version triggers also publishing
# a new "stable" version ("production").
publish-stable:
  extends: .publish-braynscircuitstudio
  variables:
    REGISTRY_IMAGE_TAG: stable
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+(\.[0-9]+)?$/


publish-dev:
  extends: .publish-braynscircuitstudio
  variables:
    REGISTRY_IMAGE_TAG: latest
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"


publish-sandbox:
  extends: .publish-braynscircuitstudio
  variables:
    REGISTRY_IMAGE_TAG: $CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG =~ /^sandbox-[1-3]$/


publish-version:
  extends: .kaniko
  stage: publish
  tags:
    - kubernetes
  variables:
    KUBERNETES_MEMORY_LIMIT: 2Gi
    KUBERNETES_MEMORY_REQUEST: 2Gi
    CI_REGISTRY_IMAGE: bbpgitlab.epfl.ch:5050/viz/brayns/braynscircuitstudio
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "master"'
  script:
    - |-
      #!/bin/bash
      
      # Here we extract the version of the app based on the package.json
      NPM_PACKAGE_VERSION=$(cat package.json | grep \"version\" | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
      echo "Package version: '$NPM_PACKAGE_VERSION'"
      
      # If it doesn't get the version string (or it's empty), the job will fail
      if [[ -z "${NPM_PACKAGE_VERSION}" ]]; then
        echo "No NPM_PACKAGE_VERSION found in package.json or the string is empty" &
        exit 1
      fi
      
      # We build the image based on the parsed NPM package version
      KANIKOPROXYBUILDARGS="--build-arg http_proxy=${http_proxy} --build-arg https_proxy=${https_proxy} --build-arg no_proxy=${no_proxy}"
      KANIKO_PUSH_ARGS="--destination $CI_REGISTRY_IMAGE:$NPM_PACKAGE_VERSION"
      echo "KANIKO_PUSH_ARGS: $KANIKO_PUSH_ARGS"
      
      if [[ -z "$DOCKERFILE_PATH" ]]; then DOCKERFILE_PATH="${BUILD_PATH}/Dockerfile"; fi
      echo DOCKERFILE_PATH=$DOCKERFILE_PATH
      /kaniko/executor --context $BUILD_PATH --dockerfile $DOCKERFILE_PATH $KANIKOPROXYBUILDARGS $DOCKER_BUILD_ARGS $KANIKO_PUSH_ARGS --skip-tls-verify --snapshotMode=redo

